import pytorch_lightning as pl
from typing import Optional, List, Tuple, Literal
import torch
from torch import nn

class TransformLatentSamplingStrategy:

    def __init__(
        self,
        transform_sequence,
        feature_extractor: nn.Module=nn.Identity(),
        neg_margin: float = 0.0, #deprecated
        index=None,
        clip_data: bool = False,
        mode: Literal["default", "double", "double_resampled"] = "default",

    ):
        """
        Samples negatives by applying random transformations in image space.

        Args:
            transform_sequence: Sequence of transformations to apply.
            feature_extractor: An nn.Module used to extract features (frozen into eval mode).
            neg_margin: Deprecated parameter.
            index: Optional custom indexing configuration.
            clip_data: Whether to clamp output image values between 0.0 and 1.0.
            mode: The transformation combination mode ('default', 'double', or 'double_resampled')
                    default: Transforms the image once using a single matrix
                    double: Transforms the image once, but uses a single matrix generated by multiplying two matrices together.Twice trasnforms by T1 and T2.
                    double_resampled: Transforms by both matrices resampling twice.
        """
        self.transform_sequence = transform_sequence
        self.feature_extractor = feature_extractor.eval()
        for p in self.feature_extractor.parameters():
            p.requires_grad = False
        self.index = index
        self.clip_data = clip_data
        self.mode = mode

    def sample(self, X_pos: torch.Tensor,seed=None) -> torch.Tensor:
        return self.sample_and_params(X_pos,seed=seed)[0]

    def sample_and_params(self, X_pos: torch.Tensor,seed=None) -> Tuple[torch.Tensor, torch.Tensor]:
        if seed is not None:
            cpu_state = torch.get_rng_state()
            cuda_state = torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None

            torch.manual_seed(seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(seed)

        batch_size = X_pos.size(0)

        params1 = self.transform_sequence.initial_param(batch_size)
        T1 = self.transform_sequence(params1)


        if self.mode == "double":
            # second transform
            params2 = self.transform_sequence.initial_param(batch_size)
            T2 = self.transform_sequence(params2)

            # combined transform
            T_combined = torch.bmm(T2, T1)

            # apply combined transform ONCE (equivalent for affine)
            X_out = self.transform_sequence.application_method(X_pos, T_combined)

            if self.clip_data and X_out.dim() == 4:
                X_out = torch.clamp(X_out, 0.0, 1.0)

            if seed is not None:
                torch.set_rng_state(cpu_state)
                if torch.cuda.is_available():
                    torch.cuda.set_rng_state_all(cuda_state)


            return X_out, T_combined

        elif self.mode == "double_resampled":
            # Apply first transform
            X1 = self.transform_sequence.application_method(X_pos, T1)


            # --- Second transform, resampled ---
            params2 = self.transform_sequence.initial_param(batch_size)
            T2 = self.transform_sequence(params2)

            # Apply second transform on already-transformed image
            X2 = self.transform_sequence.application_method(X1, T2)

            # Combined transform T2 ∘ T1
            T_combined = torch.bmm(T2, T1)

            if self.clip_data and X2.dim() == 4:
                X2 = torch.clamp(X2, 0.0, 1.0)

            if seed is not None:
                torch.set_rng_state(cpu_state)
                if torch.cuda.is_available():
                    torch.cuda.set_rng_state_all(cuda_state)

            return X2, T_combined


        # Apply first transform
        X1 = self.transform_sequence.application_method(X_pos, T1)


        X_trans = X1
        T = T1

        if self.clip_data and X_trans.dim() == 4:
            X_trans = torch.clamp(X_trans, 0.0, 1.0)

        if seed is not None:
            torch.set_rng_state(cpu_state)
            if torch.cuda.is_available():
                torch.cuda.set_rng_state_all(cuda_state)
        return X_trans, T

    def get_identity_transform(self,batch_size) -> torch.Tensor:
        """
        Generates identity transformation matrices for the given batch size.

        Args:
            batch_size: The number of matrices to generate.

        Returns:
            A batch of identity transformation matrices.
        """
        params = self.transform_sequence.get_identity_parameters(batch_size)


        T = self.transform_sequence(params)
        assert torch.allclose(T, torch.eye(T.size(-1), device=T.device,dtype=T.dtype).unsqueeze(0).expand(batch_size, -1, -1)), "Identity transform is not identity matrix!"

        return T

    def identity_params(self, batch_size) -> torch.Tensor:

        return self.transform_sequence.get_identity_parameters(batch_size)

    def identity_transform(self, batch_size) -> torch.Tensor:
        return self.get_identity_transform(batch_size)
